// src/data.js

const dataShape = [
  {
    // "id": 16, // generated by dB
    "imdb_id": "tt9214772", // text
    "title": "Monkey Man", // text
    "year": 2024, // int2
    "runtime": "2:01:36", // text
    "rating": "R", // text
    "poster": "https://image.tmdb.org/t/p/original/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg", // text
    "genres": [
      "Action",
      "Thriller"
    ] // json
  }
]

export default dataShape